Traceback (most recent call last):
  File "/home/stefan/UNI/Mustererkennung/ue5/cifar10/ex3.py", line 176, in <module>
    main(sys.argv)
  File "/home/stefan/UNI/Mustererkennung/ue5/cifar10/ex3.py", line 69, in main
    b1 = np.load('dataset/batch1.npy')
  File "/home/stefan/anaconda3/envs/tf-pose/lib/python3.6/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/batch1.npy'
